import numpy as np
dataframes_list = ['_dataR_EDpat','_dataR_EDday','_dataR_EDweek','_dataR_EDmon',
'_dataR_IPpat','_dataR_IPday','_dataR_IPweek','_dataR_IPmon',
'_dataRAW']

dataRAW_expected_dtypes = {
'dept_patid':[np.float,np.int,np.int64,np.str],
'hosp_patid':[np.float,np.int,np.int64,np.str],
'age':[np.int,np.int64],
'gender':[np.object],
'site':[np.object],
'arrive_date':[np.object],
'arrive_time':[np.object],
'arrive_datetime':[np.dtype('datetime64[ns]')],
'arrive_mode':[np.object],
'arrive_hour':[np.object],
'arrive_dayofweek':[np.object],
'arrive_month':[np.object],
'arrive_weekday_name':[np.object],
'first_triage_time':[np.object],
'first_triage_datetime':[np.dtype('datetime64[ns]')],
'first_dr_time':[np.object],
'first_dr_datetime':[np.dtype('datetime64[ns]')],
'first_adm_request_time':[np.object],
'first_adm_request_datetime':[np.dtype('datetime64[ns]')],
'adm_referral_loc':[np.object],
'depart_time':[np.object],
'depart_datetime':[np.dtype('datetime64[ns]')],
'depart_method':[np.object],
'depart_hour':[np.object],
'depart_dayofweek':[np.object],
'depart_month':[np.object],
'depart_weekday_name':[np.object],
'waiting_time':[np.float],
'breach_flag':[np.int],
'adm_flag':[np.int],
'stream':[np.float,np.int,np.int64,np.str],
'minutes_today':[np.int],
'minutes_tomo':[np.int],
'breach_datetime':[np.dtype('datetime64[ns]')]
}

dataRAW_expected_cols = ['hosp_patid',
'age',
'gender',
'arrive_datetime',
'arrive_mode',
'arrive_hour',
'arrive_dayofweek',
'arrive_month',
'arrive_weekday_name',
'first_triage_datetime',
'first_dr_datetime',
'first_adm_request_datetime',
'adm_referral_loc',
'depart_datetime',
'depart_method',
'depart_hour',
'depart_dayofweek',
'depart_month',
'depart_weekday_name',
'waiting_time',
'breach_flag',
'adm_flag',
'stream',
'minutes_today',
'minutes_tomo',
'breach_datetime']
